version: "3"

volumes:
  django_static_volume: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: demo_production_django
    container_name: django
    volumes:
      - .:/app:z
      - django_static_volume:/app/backend/django_static
    env_file:
      - ./.envs/.production/.aws
      - ./.envs/.production/.django
    network_mode: host
    command: /start
